### ISSUE TITLE
Topics in boards disappearing 

### ISSUE THREAD

**Issue by madmadisson** [ConnorWiseman/jcink-custom-structure#10]
Our staff have noticed topics in certain boards disappearing [in our forum](http://leuciarpg.com/). They appear in the index page of our forum, but once you click on them the threads do not appear.  We've had the following errors:

```
customTopics.init({
html: "<div id='topicstuffs'><div class='topicspot'>{%folder}<br>{%title}<div style='font-size:10px; text-transform:lowercase;'>{%description}</div><div style='font-size:10px;'>started by {%starter}</div></div><div class='repliess'>{%replies}<div style='font-size:10px;'>replies</div></div><div class='viewss'>{%views}<div style='font-size:10px;'>views</div></div><div class='lastposty'>most recent activity<div style='font-size:10px;'>{%date}<br>{%author}</div></div><div class='checkyy'>{%checkbox}</div></div>",
conf: {
 target:    "board",
 announcementsDefault:  "ANNOUNCEMENTS",
 pinnedDefault:  "IMPORTANT TOPICS",
 regularDefault:  "FORUM TOPICS",
 noTopics:  "No topics were found. This is either because there are no topics in this forum, or the topics are older than the current age cut-off."
}
}); 
```

On my chrome console I would get this message:

> The custom forum structure script suite is outdated. A new release is available, and upgrading is highly advised: https://github.com/ConnorWiseman/jcink-custom-structure

But the script is indeed updated with the 1.8.1 (March 2016) version. We tried uploading the javascript ourselves, but it doesn't seem to load, so we switched it back to the one hosted by Elegant Expressions. We noticed that without the elegant expressions javascript the boards worked as they should.

We went through all the boards, and some do not show the threads, while others do. I checked their settings and permissions, which vary between the ones we cannot see, yet their setting are all similar (to even the boards we can see). I can't seem to find a correlating issue between them.

I decided to search the support forums and did find [this thread](http://forum.jcink.com/index.php?showtopic=25836). Not sure if it will be helpful in discerning what the issue could be.

EDIT: [We've read this](http://forum.jcink.com/index.php?showtopic=24248) and are currently waiting for our admin to try these temporary fixes.

**Comment by ConnorWiseman** [comment]
I can confirm that you're using the previous version of the script. The objects created by the current edition of the script all use an `initialize` method instead of the old `init` method, which is what you're using to inject markup into the page. At the moment, the only instance of any version of the script I could find in your forum markup was [this file on line 3](http://files.jcink.net/html/cfs.min_2014.js)\- but it's possible you previously installed both scripts by mistake, then only ever used the old one.

They don't conflict, but for best performance make sure you're using only the file linked to in the [Installation section](https://github.com/ConnorWiseman/jcink-custom-structure#installation) of the repository README, and not the [old one](http://www.elegantexpressions.us/black/cfs.min.js). You can host your own copy or use the one provided on Elegant Expressions- as long as it's the new one, you ought to be fine.

Please also note that due to feature additions and removals to both Jcink and the script since February 2014, the new one is not backwards compatible with the old one. You'll need to go through the code you've been using previously and reconcile it with the changes listed in each module's documentation in the readme.

Going forward, using Jcink's upcoming HTML templates feature may be a better alternative to this script, unless you specifically require programmatic access to any of the data being displayed on your forum.

**Comment by ConnorWiseman** [comment]
Also, the new HTML templates feature is testable as of... recently, I'm not exactly sure when. https://twitter.com/Jcink/status/760894855815933953
