### ISSUE TITLE
custom posts

### ISSUE THREAD

**Issue by spoopyem** [ConnorWiseman/jcink-custom-structure#12]
So this question has already been asked in a way, but I'm going to ask again and hope for a different answer.  Concerning custom posts, there's no way to enter {{customField#}}, correct?  As in, when working with in the .customPosts area, custom fields cannot be used in any way, shape, or form?  This would not be within the mini profile, where I know the custom fields work as .  Also, the custom fields were enabled on the jcink site when this was tested for.  I guess I was also wondering if there was any way for {{customField#}}s to be added to the custom posts section of cfs?

**Comment by ConnorWiseman** [comment]
The script is only intended to parse the hard-coded values that appear in predictable places in the source code generated by the modified IPB software being run by the Jcink service, i.e., on pages that don't change and always follow (give or take) the same format. Likely candidates for this include user profiles, the forum index, and individual posts. The exact content of posts vary, but the relative location on the page of their contents is predictable.

Because the mini-profile templates you're referring to can be modified and are often considerably different on different hosted forums, to say nothing of including incorrect coding style that must also be accounted for, their contents are neither hard-coded nor predictable, even though their contents are guaranteed to display in the same place in the page every time.

In order to make custom fields available in the way you request, every mini-profile template would need to include custom fields in a specific element in a structure that follows a specific pattern, which is not a feature provided by the board software by default and is more work than most individuals are willing to put in for a mere re-skinning.

Realistically, there is no way to elegantly make such a feature work consistently for everyone under every set of circumstances. If there was some kind of exposed database API, we might be able to leverage that to get the necessary data without having to read it from the page source, but last I heard development on that was cancelled (and if it weren't, such an API would make the rest of this script utterly pointless).

It's probably not the answer you're looking for, but ultimately you're better off using the `<!-- |field_#| -->` variables in the mini-profile templates instead.
