### ISSUE TITLE
sub-subforums links don't display

### ISSUE THREAD

**Issue by geminithrall** [ConnorWiseman/jcink-custom-structure#13]
Hi there. I've ran into a problem with sub-subforum links (as in, a tertiary forum, main forum->subforum->sub-subforum (not sure what else to call it)). Subforum links display fine on the main board index, but if I go to browse into a forum to check out the subforums, the links to the sub-subforum links don't display unless I'm logged out of my account. I've already checked and re-checked to ensure it wasn't a simple permission error. If I click browse into the subforum, the sub-subforum will display fine, just the link to it doesn't in the subforums list. If I move the the sub-subforum out of the subforum to have the main forum be its parent again, its link displays fine on the main board index.

I'm not sure if I'm making any sense so I'm going to link to my board.
http://thralldom.jcink.net/ is the main board, http://thralldom.jcink.net/index.php?showforum=10 is a forum that has subforums. The 'want ads' forum has a subforum, http://thralldom.jcink.net/index.php?showforum=12 whose link doesn't display properly when people are logged in, despite the permission mask being set to admins and members being able to view/post/edit/etc.

I'm not seeing anything in my code that'd be displaying subforum links fine on the index but nowhere else. If you have any insight, that would be great!

**Comment by ConnorWiseman** [comment]
I think I understand what you're saying! Everything displays correctly if you're not signed in, but if you are signed in, links to subforums nested within other forums or subforums aren't rendering properly. At a glance I can see there's nothing wrong with the way you configured the script to work, so the problem you're experiencing is not on your end.

I registered a test account (named `Test`, for the record) to check the behavior for myself and was able to replicate the problem. After poking around in the page source and the browser console I can confirm that this is a bug, but it's a new one. I haven't updated this script for a little while but, as far as I knew, this wasn't one of the two unfixed problems I know it does have.

My conclusion is that something in the HTML being pushed out by the modified software that powers Jcink may have been changed recently and that's resulted in this bug, but exactly what that change is, I couldn't tell you.

Would it be possible to obtain a copy of the affected skin through the skin exporter? It would make looking into this issue much, much easier for me.

In the meantime- [HTML Template Sets](http://forum.jcink.com/?&showtopic=26180&st=0&#entry191918) have been released for public beta testing and they may be a more viable option for restructuring your forum moving forward. This is not the first time an unannounced change in raw markup output has introduced incompatibility to the script and it's not likely to be the last, especially as I move away from the project because of other obligations in my life. There are no release notes or notifications when something on the back end changes like this; it's always been a game of waiting for someone to point out a problem for me, and the process of scouring the source for some minute detail and then patching the script to account for the change takes time.

With built-in templates, however, you won't have to worry about third-party compatibility to catch up since you'll have taken the raw markup into your own hands in the first place. You can read more about the new templates on [the wiki](http://jcink.com/main/wiki/jfh-html-templates) if you're interested.

**Comment by geminithrall** [comment]
Ah, okay that makes sense. Thanks for your quick response! I'll look into the template sets.

Here's the exported skin:
[Thralldom-Full.zip](https://github.com/ConnorWiseman/jcink-custom-structure/files/490743/Thralldom-Full.zip)

**Comment by ConnorWiseman** [comment]
Great! I'll take a look under the hood and make sure any change I make to the default skin also works for the skin you're using on your forum.

**Comment by ConnorWiseman** [comment]
I think I've narrowed this down to an inconsistency in the way subforum links are rendered on the index when compared to their counterparts inside the topic view page; the [subforum links macros](http://jcink.com/main/wiki/jfb-skinning-macros#subforum_links_macros) aren't present on the latter. Going to figure out how to reconcile the differences and see if I can get the output to play nicely.

**Comment by geminithrall** [comment]
Nice! For the record, the problem went away when applying the HTML template
thing, so if you can't work out a fix, no sweat! Thanks for bringing that
to my attention.

**Comment by ConnorWiseman** [comment]
No worries! This is fixed, but I've lost my SFTP credentials for Elegant Expressions so it'll be about 24 hours before the update goes live for everyone still using the script. In the meanwhile, manually hosting a copy should do the trick.

Glad to hear the new template features work just as well for you! Best of luck in the future.
