### ISSUE TITLE
Sub Forums not Showing

### ISSUE THREAD

**Issue by Sabiruna** [ConnorWiseman/jcink-custom-structure#14]
I saw a thread on this and it said there was a fix, but I didn't see the fix up anywhere!  Basically on Jcink I have forums, then sub forums.  Then subforums off of that.  For some reason, it will only show one sub sub forum listed instead of the three that are actually there.

**Comment by ConnorWiseman** [comment]
Yeah, I'm sorry- I never did get around to reacquiring my SFTP credentials for Elegant Expressions, so I never actually managed to upload the 1.8.2 fix for this the way I promised to before. I apologize to you and @geminithrall, and anyone else who still depends on this script, for that.

I'll send the domain owner an email tonight, but until she gets back to me, it's still possible to temporarily [host your own](https://github.com/ConnorWiseman/jcink-custom-structure#installation)(more specifically, the "raw" version of the file available [here](https://raw.githubusercontent.com/ConnorWiseman/jcink-custom-structure/master/src/cs.min.js)) through Jcink's [file manager](http://jcink.com/main/wiki/jfb-filemanager#uploading_new_files) instead of using the pre-hosted copy.

Going forward, however, I really do suggest you begin working with the new HTML Templates feature instead (see [the feature beta testing announcement](http://forum.jcink.com/?&showtopic=26180&st=0&#entry191918) for details and the tail end of [this reply](https://github.com/ConnorWiseman/jcink-custom-structure/issues/13#issuecomment-249308793) for more reasons why). The long and short of it is that because these templating features are not dependent on third-party code, they will more resilient to service-specific changes and quirks like the one that introduced this bug.

Hope that helps!

**Comment by ConnorWiseman** [comment]
And as of just now, 1.8.2 should be live. Apologies again for forgetting!
